# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Source Events

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  Source runs peer learning events for people to create the education they need.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://events.source.institute" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /:title.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
formbox-url: "https://sourceinstitute.typeform.com/to/xrL0RX"
